title: Kevin Mena
tagline: Site Tagline
author :
	name : Kevin Mena
	email : kevinm.developer@gmail.com
	github : KevinMena
	twitter : KevinAMena
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-remote-theme
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md